# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: false

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get update
  - sudo apt-get install libjq-dev
  - sudo apt-get install libprotobuf-dev
  - sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev
  - sudo apt-get install libudunits2-dev
  - sudo apt-get install libv8-3.14-dev
  - sudo apt-get install libgeos-c1v5 libspatialite5 libgdal1h libgdal-dev libgdal1-dev gdal-abi-2-1-0 libproj-dev gdal-bin

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
